# Generated by Django 6.0.5 on 2026-05-07

import django.utils.timezone
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0003_alter_article_embedding_alter_article_full_text_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users_user',
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(help_text='Anonymous session ID. Later replaced by user FK.', max_length=128)),
                ('key', models.CharField(help_text="Preference key, e.g. 'muted_topics', 'preferred_sources'", max_length=100)),
                ('value', models.JSONField(blank=True, default=dict, help_text='Preference value as JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('session_id', 'key')},
            },
        ),
        migrations.CreateModel(
            name='UserInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(help_text='Anonymous session ID (UUID). Later replaced by user FK.', max_length=128)),
                ('interaction_type', models.CharField(choices=[('click', 'User clicked on the cluster'), ('save', 'User saved/bookmarked the cluster'), ('dwell', 'User spent significant time on the cluster')], help_text='Type of interaction recorded', max_length=10)),
                ('dwell_seconds', models.PositiveIntegerField(default=0, help_text="Time spent on the cluster in seconds (for 'dwell' type)")),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this interaction was recorded')),
                ('cluster', models.ForeignKey(help_text='The cluster the user interacted with', on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='articles.topiccluster')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session_id', '-created_at'], name='users_useri_session_f9bc77_idx')],
            },
        ),
    ]
