# Generated by Django 5.2.8 on 2026-05-20 16:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='monthly_ai_chat_limit',
            field=models.IntegerField(default=200),
        ),
        migrations.AddField(
            model_name='user',
            name='monthly_ai_chat_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='quota_reset_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userinteraction',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When this interaction was recorded'),
        ),
    ]
