# Generated by Django 6.0.5 on 2026-05-05 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('source_type', models.CharField(choices=[('web', 'Web Scraper'), ('rss', 'RSS Feed'), ('api', 'API')], default='web', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order in tab bar')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('url', models.URLField()),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('full_text', models.TextField(blank=True, default='')),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('summary', models.TextField(blank=True, default='')),
                ('embedding_id', models.CharField(blank=True, default='', max_length=255)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='articles.source')),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.AddField(
            model_name='source',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='articles.tab'),
        ),
        migrations.CreateModel(
            name='TopicCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_id', models.UUIDField()),
                ('summary', models.TextField()),
                ('sources', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('primary_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clustered_as_primary', to='articles.article')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['-published_at'], name='articles_ar_publish_c1a2fc_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['source', '-published_at'], name='articles_ar_source__d48552_idx'),
        ),
        migrations.AddIndex(
            model_name='topiccluster',
            index=models.Index(fields=['-created_at'], name='articles_to_created_cb1601_idx'),
        ),
        migrations.AddIndex(
            model_name='topiccluster',
            index=models.Index(fields=['topic_id'], name='articles_to_topic_i_82589b_idx'),
        ),
    ]
