# Generated by Django 6.0.5 on 2026-05-05 20:52

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='embedding_id',
        ),
        migrations.AddField(
            model_name='article',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, null=True, dimensions=768),
        ),
    ]
