# Generated by Django 6.0.5 on 2026-05-07 05:33

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_remove_article_embedding_id_article_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, help_text='768-dim embedding vector for similarity search', null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='full_text',
            field=models.TextField(blank=True, default='', help_text='Full article body (truncated to ~2000 chars by scraper)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='published_at',
            field=models.DateTimeField(blank=True, help_text='Original publication time from the source', null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='summary',
            field=models.TextField(blank=True, default='', help_text='AI-generated one-line summary'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(help_text='Headline of the article', max_length=1000),
        ),
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.URLField(help_text='Canonical URL of the original article'),
        ),
        migrations.AlterField(
            model_name='source',
            name='active',
            field=models.BooleanField(default=True, help_text='Whether this source should be scraped'),
        ),
        migrations.AlterField(
            model_name='source',
            name='category',
            field=models.ForeignKey(help_text='Which tab this source belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='articles.tab'),
        ),
        migrations.AlterField(
            model_name='source',
            name='name',
            field=models.CharField(help_text="Source name, e.g. 'NDTV', 'BBC News'", max_length=200),
        ),
        migrations.AlterField(
            model_name='source',
            name='url',
            field=models.URLField(help_text='Base URL or RSS feed URL for this source'),
        ),
        migrations.AlterField(
            model_name='tab',
            name='name',
            field=models.CharField(help_text="Human-readable tab name, e.g. 'India'", max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='tab',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order in the tab bar (lower = leftmost)'),
        ),
        migrations.AlterField(
            model_name='tab',
            name='slug',
            field=models.SlugField(help_text="URL-safe slug, e.g. 'india'", unique=True),
        ),
        migrations.AlterField(
            model_name='topiccluster',
            name='primary_article',
            field=models.ForeignKey(help_text='The newest/most representative article in this cluster', on_delete=django.db.models.deletion.CASCADE, related_name='clustered_as_primary', to='articles.article'),
        ),
        migrations.AlterField(
            model_name='topiccluster',
            name='sources',
            field=models.JSONField(blank=True, default=list, help_text='List of source names contributing to this cluster'),
        ),
        migrations.AlterField(
            model_name='topiccluster',
            name='summary',
            field=models.TextField(help_text='AI-generated unified summary (~60-80 words, InShorts style)'),
        ),
        migrations.AlterField(
            model_name='topiccluster',
            name='topic_id',
            field=models.UUIDField(help_text='AI-generated unique ID for the story cluster'),
        ),
    ]
