# Generated by Django 5.2.8 on 2026-05-20 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_topiccluster_suggested_prompts'),
    ]

    operations = [
        migrations.AddField(
            model_name='topiccluster',
            name='keywords',
            field=models.JSONField(blank=True, default=list, help_text="Extracted keywords for search and autocomplete, e.g. ['election', 'modi']"),
        ),
        migrations.AlterField(
            model_name='article',
            name='full_text',
            field=models.TextField(blank=True, default='', help_text='Clean plain-text article body (up to ~8000 chars from scraper)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.URLField(help_text='Canonical URL of the original article', max_length=2048),
        ),
        migrations.AlterField(
            model_name='topiccluster',
            name='summary',
            field=models.TextField(help_text='AI-generated unified summary (~100-120 words, InShorts style)'),
        ),
    ]
