# Generated by Django 5.2.8 on 2026-05-10 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0003_alter_article_embedding_alter_article_full_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('far-assistant', 'Assistant'), ('system', 'System')], max_length=20)),
                ('content', models.TextField(help_text='The message text.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cluster', models.ForeignKey(help_text='The topic cluster this chat belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='articles.topiccluster')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
