# Generated by Django 6.0.5 on 2026-05-05 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScraperConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selector_title', models.CharField(blank=True, default='', max_length=500)),
                ('selector_content', models.CharField(blank=True, default='', max_length=500)),
                ('selector_date', models.CharField(blank=True, default='', max_length=500)),
                ('custom_headers', models.JSONField(blank=True, default=dict)),
                ('delay_min', models.FloatField(default=1.0)),
                ('delay_max', models.FloatField(default=2.0)),
                ('enabled', models.BooleanField(default=True)),
                ('source', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scraper_config', to='articles.source')),
            ],
        ),
    ]
