# Generated by Django 6.0.5 on 2026-05-07 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraperconfig',
            name='custom_headers',
            field=models.JSONField(blank=True, default=dict, help_text='Additional HTTP headers for the scraper'),
        ),
        migrations.AlterField(
            model_name='scraperconfig',
            name='delay_max',
            field=models.FloatField(default=2.0, help_text='Maximum delay in seconds between requests'),
        ),
        migrations.AlterField(
            model_name='scraperconfig',
            name='delay_min',
            field=models.FloatField(default=1.0, help_text='Minimum delay in seconds between requests'),
        ),
        migrations.AlterField(
            model_name='scraperconfig',
            name='enabled',
            field=models.BooleanField(default=True, help_text='Whether this scraper is active'),
        ),
        migrations.AlterField(
            model_name='scraperconfig',
            name='selector_content',
            field=models.CharField(blank=True, default='', help_text="CSS selector for the content element (e.g. 'article, .story-body')", max_length=500),
        ),
        migrations.AlterField(
            model_name='scraperconfig',
            name='selector_date',
            field=models.CharField(blank=True, default='', help_text='CSS selector for the date element', max_length=500),
        ),
        migrations.AlterField(
            model_name='scraperconfig',
            name='selector_title',
            field=models.CharField(blank=True, default='', help_text="CSS selector for the title element (e.g. 'h1, .story-title')", max_length=500),
        ),
    ]
