# Generated by Django 5.2.8 on 2026-05-10 19:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email address for the daily digest', max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the subscriber is currently active')),
                ('tabs', models.JSONField(blank=True, default=list, help_text="Preferred news tabs (e.g. ['india', 'sports'])")),
                ('unsubscribe_token', models.UUIDField(default=uuid.uuid4, help_text='Unique token for unsubscribe links', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the subscriber opted in')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last time the subscription was updated')),
            ],
            options={
                'db_table': 'digest_email_subscriber',
                'ordering': ['-created_at'],
            },
        ),
    ]
